#!/bin/bash
set -e

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
fi

SPOTDL_DIR="/usr/share/ongaku/spotdl-custom"
if [ -d "$SPOTDL_DIR" ]; then
    find "$SPOTDL_DIR/bin" -type f -exec chmod +x {} \;
fi

exit 0
